### ISSUE TITLE
Performance tests? Or is it *not* a race?

### ISSUE THREAD

**Issue by Danny-Engelman** [alexspirgel/children-loaded#1]
But have you tested what you gained?

Your code, which needs to be loaded **before** you can use it, and requires extra ``async`` syntax on the ``connectedCallback``

Your code **IS** "faster" on direct comparison with ``requestAnimationFrame`` and ``setTimeout`` "solutions" (not requiring _any_ extra code)

But **not using** your code, those native 'hacks' **are** "faster"...

![](https://i.imgur.com/wFLtBxm.png)

source: https://jsfiddle.net/WebComponents/0381j2og/

Just like WebReflection his solution; you proved you can _get-ahead-of-the-line_

![](https://i.imgur.com/LpB5DI6.png)

Question is, what is really gained? Is it a race or about getting past that line? (knowing, for sure, child elements are parsed)

You are adding code complexity and code dependency to gain 1 or 2 ms? 
You can only tell by A-B testing this in a real application...

Then again, are we re-writing our FP to **_faster_** for-loops?

**Comment by alexspirgel** [comment]
Hi @Danny-Engelman thanks for checking out my work, and thanks for posting a code example. I was not not aware of the `requestAnimationFrame` or `setTimeout` approaches to this problem.

At first glance when I tested them myself, they seemed to work great, both performed faster than my solution in this repository, but I was a little suspicious. Is there something inherit to `requestAnimationFrame` and `setTimeout` that they will wait for all the child elements I need to be loaded. How do they know when to call back at the right time? Are they just waiting for the whole document to be loaded?

**As I suspected they both appear to be race conditions.** In many scenarios `requestAnimationFrame` and `setTimeout` will technically work, as the race condition appears to currently have a bit of head room. On my machine the race condition will fail somewhere around 1000 text paragraphs of child elements, which seems like it would cover most use cases, but that will change depending on the device and how browsers differ from each other and themselves in the future. The `requestAnimationFrame` and `setTimeout` functions were not built for this purpose, who knows how they will interact with  this scenario in the future? For these reasons I do not think they are a viable solution to the problem.

I found results when testing using jsfiddle to be very inconsistent so I have added essentially a race condition test to my demo page http://alexanderspirgel.com/children-loaded/demo to illustrate the issue. Let me know if my findings also match yours.

As for your comment:

> and requires extra async syntax on the connectedCallback

This is just how I chose to implement because I prefer the `async` `await` syntax. It returns true or a promise. There is no reason you would **have** to add the `async` syntax to `connectedCallback`. You can see in the updated demo page code how I chose to implement it using the `.then` syntax. The `.then` syntax is very similar to that of `requestAnimationFrame` or `setTimeout`.

**Comment by Danny-Engelman** [comment]
Tnx, great code rewrite, and great **race**, and totally valid arguments.

I had to reload 50 times for a value under 1000:

![](https://i.imgur.com/DrD8ukk.png)

300 million years ago, in Computer Science class, we had to program **fail-save** programs.
Our professor (well, actually his teaching assistants) literally pulled the power plug, when we were testing our programs.

And then you grow up, enter the real world, and become a program(mers) manager.
And you learn the cost of software is not its 100% correctness. But programmers writing too many lines of code.

I now teach. And never pull that plug.
And, in this case, teach people ``setTimeout`` is not the best, but the best method for the team.

I've done a lot of (small, as they should be) components over the years. If I ever had **25** child-elements, it was a lot.

**Comment by alexspirgel** [comment]
Thanks for your insights. You are definitely correct that in 99% of scenarios, using `requestAnimationFrame ` or `setTimout` will work well, but personally, I will reach for the mutation observer approach most of the time because I prefer the certainty.

Also it may be worth mentioning the pros and cons of both approaches when you teach (if you don't already).

Anyway thanks for raising the issue, I'll close it out now.
